task: pose_estimation
model: RACE6Dv2
criterion: RACE6Dv2Criterion
postprocessor: RACE6Dv2PostProcessor
use_focal_loss: True
num_keypoints: 32
eval_spatial_size: [480, 640] # h w

RACE6Dv2:
  backbone: PResNet
  encoder: HybridEncoder
  decoder: RACE6DTransformer_V2

PResNet:
  depth: 50
  variant: d
  freeze_at: -1
  return_idx: [1, 2, 3]
  num_stages: 4
  freeze_norm: False
  pretrained: True

HybridEncoder:
  in_channels: [512, 1024, 2048]
  feat_strides: [8, 16, 32]

  # intra
  hidden_dim: 256
  use_encoder_idx: [2]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.
  enc_act: 'gelu'

  expansion: 1.0
  depth_mult: 1
  act: 'silu'

RACE6DTransformer_V2:
  feat_channels: [256, 256, 256]
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  num_levels: 3
  num_layers: 3
  num_queries: 100
  eval_idx: -1
  num_points: [4, 4, 4]
  cross_attn_method: default
  query_select_method: default
  vis_enc: True

RACE6Dv2PostProcessor:
  num_top_queries: 100
  remap_mscoco_category: False

RACE6Dv2Criterion:
  weight_dict: {loss_mal: 1, loss_keypoints: 1, loss_pose: 5}
  enc_weight_dict: {loss_mal: 1}
  losses: ['mal', 'keypoint', 'pose']
  alpha: 0.75
  gamma_pos: 1.0
  gamma_neg: 2.0

  matcher:
    type: HungarianMatcherV2
    weight_dict: {cost_class: 2, cost_add: 5}
    alpha: 0.25
    gamma: 2.0
